# Generated by Django 5.1.7 on 2025-05-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_wtuser_options_wtuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wtuser',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
